blog_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
    path('users/', include('users.urls')),
]

blogs/urls.py
from django.urls import path
from . import views

app_name = 'blogs'

urlpatterns = [

    path('tags/', views.TagList.as_view(), name='tag_list'),
    path('tags/create/', views.TagCreate.as_view(), name='tag_create'),

    path('', views.BlogPostList.as_view(), name='blogpost_list'),
    path('tags/<slug:slug>/', views.TagBlogPostList.as_view(), name='tag_blogpost_list'),
    path('user/<slug:slug>', views.AuthorBlogPostList.as_view(), name='author_blogpost_list'),
    path('saved/', views.SavedBlogPostList.as_view(), name='saved_blogpost_list'),

    path('create/', views.BlogPostCreate.as_view(), name='blogpost_create'),
    path('<slug:slug>/', views.BlogPostDetail.as_view(), name='blogpost_detail'),
    path('update/<slug:slug>/', views.BlogPostUpdate.as_view(), name='blogpost_update'),
    path('delete/<slug:slug>/', views.BlogPostDelete.as_view(), name='blogpost_delete'),

    path('create-comment/<slug:slug>/<str:content>/', views.create_comment, name='create_comment'),
    path('delete-comment/<int:commentId>/', views.delete_comment, name='delete_comment'),

    path('save-blogpost/<slug:slug>/', views.save_blogpost, name='save_blogpost'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.loginView, name='login'),
    path('register/', views.registerView, name='register'),
    path('logout/', views.logoutView, name='logout'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

from django.utils.text import slugify
from django.urls import reverse
from django.utils import  timezone

# Create your models here.


class Tag(models.Model):

    name = models.CharField(max_length=31)
    slug = models.SlugField(blank=True, unique=True, db_index=True, editable=False)


    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("blogs:tag_blogpost_list", kwargs={"slug": self.slug})
    


class BlogPost(models.Model):

    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=63)
    content = models.TextField()
    
    created_time = models.DateTimeField(auto_now_add=True)
    last_updated_time = models.DateTimeField(auto_now=True)

    tags = models.ManyToManyField(Tag, blank=True,related_name='posts')
    saved_by = models.ManyToManyField(User, blank=True,related_name='favorites')
    
    slug = models.SlugField(blank=True, unique=True, db_index=True, editable=False)


    class Meta:
        ordering = ['-last_updated_time']

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("blogs:blogpost_detail", kwargs={"slug": self.slug})
    
    @property
    def is_saved(self, username):
        return self.saved_by.filter(username=username).exists()
    


class Comment(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    blogpost = models.ForeignKey(BlogPost, on_delete=models.CASCADE)

    content = models.TextField()

    created_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_time']

    def __str__(self):
        return self.content

blogs/forms.py
from django.forms import ModelForm, Textarea, TextInput
from .models import BlogPost, Tag, Comment

class BlogPostForm(ModelForm):
    
    class Meta:
        model = BlogPost
        fields = [
            'title',
            'content',
            'tags',
        ]

        help_texts = {
            "tags": ("Hold down “Ctrl”, or “Command” on a Mac, to select more than one."),
        }
        widgets = {
            "title": TextInput(attrs={'class':'form-control'}),
            "content": Textarea(attrs={'class':'textarea form-control'})

        }




class TagForm(ModelForm):

    class Meta:
        model = Tag
        fields = '__all__'

    

class CommentForm(ModelForm):

    class Meta:
        model = Comment
        fields = ['content',]

blogs/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.db.models import Count
from django.forms.models import BaseModelForm
from django.shortcuts import render, redirect
from django.views import generic
from django.urls import reverse_lazy
from django.http import HttpResponse, JsonResponse

from django.utils.text import slugify

from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib import messages

from .models import BlogPost, Tag, Comment
from .forms import BlogPostForm, TagForm, CommentForm




###############   LISTING     #################

class BlogPostList(generic.ListView):

    model = BlogPost
    template_name = 'blogs/blogpost_list.html'


class TagBlogPostList(generic.ListView):

    template_name = 'blogs/blogpost_list_tag.html'
    def get_queryset(self):
        tag = Tag.objects.get(slug = self.kwargs.get('slug'))
        return tag.posts.all()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag'] = Tag.objects.get(slug = self.kwargs.get('slug')).name
        return context

    
    

class AuthorBlogPostList(generic.ListView):

    def get_template_names(self):
        if self.request.user == User.objects.get(username = self.kwargs.get('slug')):
            template_name =  'blogs/blogpost_list_user.html'
        else:
            template_name =  'blogs/blogpost_list_author.html'
        
        return template_name
    

    def get_queryset(self):
        return BlogPost.objects.filter(author__username = self.kwargs.get('slug'))
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = self.kwargs.get('slug')
        return context





class SavedBlogPostList(LoginRequiredMixin, generic.ListView):

    login_url = "users:login"

    template_name = 'blogs/blogpost_list_saved.html'
    def get_queryset(self):
        user = self.request.user
        return user.favorites.all()
    


#################    BLOGPOST OPERATIONS    #################


class BlogPostDetail(generic.DetailView):


    template_name = 'blogs/blogpost_detail.html'
    model = BlogPost
    


class BlogPostCreate(LoginRequiredMixin, generic.CreateView):

    login_url = "users:login"

    template_name = 'blogs/blogpost_create.html'
    model = BlogPost
    form_class = BlogPostForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

        


class BlogPostUpdate(LoginRequiredMixin, generic.UpdateView):

    login_url = "users:login"

    template_name = 'blogs/blogpost_update.html'
    model = BlogPost
    form_class = BlogPostForm


class BlogPostDelete(LoginRequiredMixin, generic.DeleteView):

    login_url = "users:login"

    model = BlogPost
    success_url = 'blogs:blogpost_list'

    def get_success_url(self):
        return reverse_lazy('blogs:blogpost_list')
    
    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)
    


def save_blogpost(request, slug):
    if request.user.is_authenticated:
        blogpost = BlogPost.objects.get(slug=slug)

        if request.user in blogpost.saved_by.all():
            blogpost.saved_by.remove(request.user)
            response_message = "Removed from saved posts."

        else:
            blogpost.saved_by.add(request.user)
            response_message = "Added to saved posts."

        return JsonResponse(response_message, safe=False)
    
    else:
        messages.error(request, "You have to login to save Posts.")

        return JsonResponse("Loginsene pic", safe=False)


###################     TAG OPERATIONS     ####################


class TagCreate(LoginRequiredMixin, generic.CreateView):

    template_name = 'blogs/tag_create.html'
    model = Tag
    form_class = TagForm

    login_url = "users:login"

    def form_valid(self, form):

        stop_limit = 3
        tags_created_by_user = self.request.session.get('tags_created_by_user', 0)

        if tags_created_by_user >= stop_limit:
            messages.warning(self.request, 'Yavaş la kaç tane açiyon.')
            return redirect('blogs:tag_list')
        
        self.request.session['tags_created_by_user'] = tags_created_by_user + 1
        return super().form_valid(form)


class TagList(generic.ListView):

    template_name = 'blogs/tag_list.html'

    def get_queryset(self):
        return Tag.objects.all().annotate(count = Count('posts')).order_by('-count')



class TagDelete(generic.DeleteView):

    model = Tag
    success_url = reverse_lazy('blogs:tag_list')

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)
    



################    COMMENT OPERATIONS    ################



def create_comment(request, slug, content):

    if request.user.is_authenticated:
    
        blogpost = BlogPost.objects.get(slug = slug)
        user = request.user
        blogpost.comment_set.create(user = user, content = content)
        return JsonResponse('helal sana goca gıral', safe=False)

    else:
        messages.error(request, "You have to login to comment.")
        return JsonResponse("Loginsene pic", safe=False)
    


def delete_comment(request, commentId):


    comment = Comment.objects.get(id = commentId)

    if request.user == comment.user:

        comment.delete()
        return JsonResponse('aferim', safe=False)
    
    else:
        messages.error(request, "You have to login to delete your comment.")
        return JsonResponse("Loginsene pic", safe=False)
    

templates/blogs/blogpost_create.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Create BlogPost{% endblock title %}


{% block body %}
    <h1>Create BlogPost</h1>   

    <form method="POST">
      {% csrf_token %}

      {% for field in form %}
        <div id="div_id_{{field.label}}" class="mb-3">
          
          {{ field.errors }}
          <label for="id_{{field.label}}" class="form-label">{{field.label}}</label> 
          {{field}}
          {{ field.help_text }}
        </div>
      {% endfor %}

      <input class="btn btn-primary" type="submit" value="Create">
    </form>

{% endblock body %}

templates/blogs/blogpost_detail.html
{% extends 'base.html' %}
{% load static %}


{% block title %}{{object.title}} {% endblock title %}




{% block body %}
    
    <!-- Page content-->

    <div class="row">
        <!-- Post content-->
        <article>
            <!-- Post header-->
            <header class="mb-4">
                <!-- Post title-->             
                                       
                <h1 class="fw-bolder" >
                    {{object.title}} 
                    <a href=""><i data-slug="{{object.slug}}" class="save-button text-dark fa fa-bookmark{% if not request.user in object.saved_by.all %}-o{% endif %}" style="font-size:30px"></i></a>
                </h1>
                {% if object.author == request.user %}
                    <div class="m2">
                        <a href="{% url 'blogs:blogpost_update' object.slug %}"><button class="btn btn-primary">Update</button></a>
                        <a href="{% url 'blogs:blogpost_delete' object.slug %}"><button class="btn btn-danger">Delete</button></a>
                    </div>
                {% endif %}
                <!-- Post meta content-->
                <div class="text-muted fst-italic mb-2">
                    By <a class="text-muted" href="{% url 'blogs:author_blogpost_list' object.author.username %}">{{object.author}}</a><br>
                    Posted on {{object.created_time}}<br>
                    {% if object.created_time != object.last_updated_time %}Updated at {{object.last_updated_time}}{% endif %} 
                </div>
                <!-- Post categories-->
                {% for tag in object.tags.all %}
                <a class="badge bg-secondary text-decoration-none text-light" href="{% url 'blogs:tag_blogpost_list' tag.slug %}">{{tag.name}}</a>
                {% endfor %}
                
            </header>
            <br>

            <!-- Post content-->
            <section class="mb-5">
                <p class="mb-4" style="font-size: 19px;">{{object.content | linebreaksbr}}</p>
            </section>
        </article>
        <br>
            
    </div>

    {% include 'blogs/comments.html' %}
{% endblock body %}

templates/blogs/blogpost_list.html
{% extends 'base.html' %}
{% load static %}


{% block title %}BlogPost App{% endblock title %}




{% block body %}


    <h1>Home</h1>
    <hr>

    {% if object_list %}
        {% for blogpost in object_list %}

            <article>

                <p class="text-muted fst-italic mb-2"><a class="text-muted" href="{% url 'blogs:author_blogpost_list' blogpost.author.username %}">{{blogpost.author}}</a> &#183; {{blogpost.created_time}}</p>            
                <h3 class="md-heading">
                    <a class="text-dark" href="{{blogpost.get_absolute_url}}">{{blogpost.title}}</a>
                    <a href=""><i data-slug="{{blogpost.slug}}" class="save-button text-dark fa fa-bookmark{% if not request.user in blogpost.saved_by.all %}-o{% endif %}" style="font-size:30px"></i></a>
                </h3>
                <p>{{blogpost.content|truncatechars:250}}... <span><a class="text-muted fst-italic" href="{{blogpost.get_absolute_url}}">read more</a></span></p>
                                        
                {% for tag in blogpost.tags.all %}
                    <a class="badge bg-secondary text-decoration-none text-light" href="{% url 'blogs:tag_blogpost_list' tag.slug %}">{{tag.name}}</a>
                {% endfor %}

            <br>                
            </article>
            <hr>
        {% endfor %}
    {% else %}
        <p style="font-size:22px;">
            Hello from a regular BlogPost app. You've already know what are you going to do but if you don't; 
            <a class="text-dark" href="{% url 'users:register' %}">Register</a>, 
            <a class="text-dark" href="{% url 'users:login' %}">Login</a>, 
            <a class="text-dark" href="{% url 'blogs:blogpost_create' %}">Create</a>! (
            <a class="text-dark" href="{% url 'blogs:tag_create' %}">Tag creation </a> 
            is also your job :))
        </p>
    {% endif %}



{% endblock body %}

templates/blogs/blogpost_list_author.html
{% extends 'base.html' %}
{% load static %}


{% block title %}{{author}}'s Posts{% endblock title %}




{% block body %}
    

<h1>{{author}} Author's Blog Posts</h1>
<hr>

{% if object_list %}
    {% for blogpost in object_list %}

        <article>

            <p class="text-muted fst-italic mb-2"><a class="text-muted" href="{% url 'blogs:author_blogpost_list' blogpost.author.username %}">{{blogpost.author}}</a> &#183; {{blogpost.created_time}}</p>            
            <h3 class="md-heading">
                <a class="text-dark" href="{{blogpost.get_absolute_url}}">{{blogpost.title}}</a>
                <a href=""><i data-slug="{{blogpost.slug}}" class="save-button text-dark fa fa-bookmark{% if not request.user in blogpost.saved_by.all %}-o{% endif %}" style="font-size:30px"></i></a>
            </h3>
            <p>{{blogpost.content|truncatechars:250}}... <span><a class="text-muted fst-italic" href="{{blogpost.get_absolute_url}}">read more</a></span></p>
                                    
            {% for tag in blogpost.tags.all %}
                <a class="badge bg-secondary text-decoration-none text-light" href="{% url 'blogs:tag_blogpost_list' tag.slug %}">{{tag.name}}</a>
            {% endfor %}

        <br>                
        </article>
        <hr>
    {% endfor %}
{% else %}
    <p>It looks like there are no post here.</p>
    <p style="font-size:22px;">It looks like there are no post here.</p>
{% endif %}

{% endblock body %}

templates/blogs/blogpost_list_saved.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Saved Posts{% endblock title %}




{% block body %}
    

<h1>Saved Blog Posts</h1>
<hr>

{% if object_list %}
    {% for blogpost in object_list %}

        <article>

            <p class="text-muted fst-italic mb-2"><a class="text-muted" href="{% url 'blogs:author_blogpost_list' blogpost.author.username %}">{{blogpost.author}}</a> &#183; {{blogpost.created_time}}</p>            
            <h3 class="md-heading">
                <a class="text-dark" href="{{blogpost.get_absolute_url}}">{{blogpost.title}}</a>
                <a href=""><i data-slug="{{blogpost.slug}}" class="save-button text-dark fa fa-bookmark{% if not request.user in blogpost.saved_by.all %}-o{% endif %}" style="font-size:30px"></i></a>
            </h3>
            <p>{{blogpost.content|truncatechars:250}}... <span><a class="text-muted fst-italic" href="{{blogpost.get_absolute_url}}">read more</a></span></p>
                                    
            {% for tag in blogpost.tags.all %}
                <a class="badge bg-secondary text-decoration-none text-light" href="{% url 'blogs:tag_blogpost_list' tag.slug %}">{{tag.name}}</a>
            {% endfor %}

        <br>                
        </article>
        <hr>
    {% endfor %}
{% else %}
    <p style="font-size:22px;">It looks like there are no post here. Let's go and get some to save!</p>
{% endif %}

{% endblock body %}

templates/blogs/blogpost_list_tag.html
{% extends 'base.html' %}
{% load static %}


{% block title %}"{{tag}}"{% endblock title %}




{% block body %}
    

<h1>"{{tag}}" Tag's Blog Posts</h1>
<hr>

{% if object_list %}
    {% for blogpost in object_list %}

        <article>

            <p class="text-muted fst-italic mb-2"><a class="text-muted" href="{% url 'blogs:author_blogpost_list' blogpost.author.username %}">{{blogpost.author}}</a> &#183; {{blogpost.created_time}}</p>            
            <h3 class="md-heading">
                <a class="text-dark" href="{{blogpost.get_absolute_url}}">{{blogpost.title}}</a>
                <a href=""><i data-slug="{{blogpost.slug}}" class="save-button text-dark fa fa-bookmark{% if not request.user in blogpost.saved_by.all %}-o{% endif %}" style="font-size:30px"></i></a>
            </h3>
            <p>{{blogpost.content|truncatechars:250}}... <span><a class="text-muted fst-italic" href="{{blogpost.get_absolute_url}}">read more</a></span></p>
                                    
            {% for tag in blogpost.tags.all %}
                <a class="badge bg-secondary text-decoration-none text-light" href="{% url 'blogs:tag_blogpost_list' tag.slug %}">{{tag.name}}</a>
            {% endfor %}

        <br>                
        </article>
        <hr>
    {% endfor %}
{% else %}
    <p style="font-size:22px;">It looks like there are no post here. <span><a href="{% url 'blogs:blogpost_create' %}">Let's create!</a></span></p>
{% endif %}

{% endblock body %}

templates/blogs/blogpost_list_user.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Your Posts{% endblock title %}




{% block body %}
    

<h1>Your Blog Posts</h1>
<hr>

{% if object_list %}
    {% for blogpost in object_list %}

        <article>

            <p class="text-muted fst-italic mb-2"><a class="text-muted" href="{% url 'blogs:author_blogpost_list' blogpost.author.username %}">{{blogpost.author}}</a> &#183; {{blogpost.created_time}}</p>            
            <h3 class="md-heading">
                <a class="text-dark" href="{{blogpost.get_absolute_url}}">{{blogpost.title}}</a>
                <a href=""><i data-slug="{{blogpost.slug}}" class="save-button text-dark fa fa-bookmark{% if not request.user in blogpost.saved_by.all %}-o{% endif %}" style="font-size:30px"></i></a>
                <a href="{% url 'blogs:blogpost_update' blogpost.slug %}"><button class="btn btn-primary ml-4">Update</button></a>
                <a href="{% url 'blogs:blogpost_delete' blogpost.slug %}"><button class="btn btn-danger">Delete</button></a>
            </h3>
            <p>{{blogpost.content|truncatechars:250}}... <span><a class="text-muted fst-italic" href="{{blogpost.get_absolute_url}}">read more</a></span></p>
                                    
            {% for tag in blogpost.tags.all %}
                <a class="badge bg-secondary text-decoration-none text-light" href="{% url 'blogs:tag_blogpost_list' tag.slug %}">{{tag.name}}</a>
            {% endfor %}

        <br>                
        </article>
        <hr>
    {% endfor %}
{% else %}
    <p style="font-size:22px;">It looks like there are no post here. <span><a href="{% url 'blogs:blogpost_create' %}">Let's create!</a></span></p>
{% endif %}

{% endblock body %}

templates/blogs/blogpost_update.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Update BlogPost{% endblock title %}


{% block body %}
    <h1>Update BlogPost</h1>   

    <form method="POST">
      {% csrf_token %}

      {% for field in form %}
        <div id="div_id_{{field.label}}" class="mb-3">
          
          {{ field.errors }}
          <label for="id_{{field.label}}" class="form-label">{{field.label}}</label> 
          {{field}}
          {{ field.help_text }}
        </div>
      {% endfor %}

      <input class="btn btn-primary" type="submit" value="Update">
    </form>

{% endblock body %}

templates/blogs/comments.html
    <!-- Comments section-->
    <section class="mb-5">
        <div class="card bg-light">
            
            <div class="card-body">
                <!-- Comment form-->
                <form id="create-comment" data-slug="{{object.slug}}" method="POST" class="mb-4">
                    {% csrf_token %}
                    <textarea id="form-input" class="form-control mb-2" name="text" placeholder="Leave a comment!" required></textarea>
                    <button class="btn btn-outline-secondary" type='submit'>Save Comment</button>
                </form>
                <!-- Comment with nested comments-->
                <h5>{{object.comment_set.all.count}} comments</h5><br>
                {% for comment in object.comment_set.all %}
                <div class="d-flex">
                    <div class="ms-3">
                        <h5 class="fw-bold">
                            {{comment.user}}
                            {% if comment.user == request.user %}
                            <a href=""><i class="delete-comment fa fa-trash-o text-dark float-right" style="font-size:21px;margin-left:12px;"></i></a>
                            <a href=""><i class="delete-cancel fa fa-times text-dark float-right" style="font-size:18px;margin-left:12px;" hidden></i></a>
                            <a href=""><i data-id="{{comment.id}}" class="delete-accept fa fa-check text-dark float-right" style="font-size:18px;margin-left:12px;" hidden></i></a>
                            {% endif %}
                            <small style="margin-left: 16px;" class="form-text fst-italic text-muted float-right">{{comment.created_time}}</small>
                        </h5>
                        <p class="ml-3">{{comment.content}} </p>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </section>

templates/blogs/tag_create.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block title %}Create Tag{% endblock title %}




{% block body %}


    <h1>Create Tag</h1>
    <form method='POST'>
        {% csrf_token %}
        {{form|crispy}}
        <button class="btn btn-success" type='submit'>Create</button>
    </form>


{% endblock body %}

templates/blogs/tag_list.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Tags{% endblock title %}




{% block body %}

    <h1>
        Tags
        <a href="{% url 'blogs:tag_create' %}"><button class="float-right btn btn-primary">Create Tag</button></a>
    </h1>
    <br>
    <hr>

    {% for tag in object_list %}

        <h5 class="md-heading"><a class="text-dark" href="{{tag.get_absolute_url}}">{{tag.name}}</a></h5>               
        <hr>

    {% endfor %}

{% endblock body %}