blog_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
    path('users/', include('users.urls')),
]

blogs/urls.py
from django.urls import path
from . import views

app_name = 'blogs'

urlpatterns = [

    path('tags/', views.TagList.as_view(), name='tag_list'),
    path('tags/create/', views.TagCreate.as_view(), name='tag_create'),

    path('', views.BlogPostList.as_view(), name='blogpost_list'),
    path('tags/<slug:slug>/', views.TagBlogPostList.as_view(), name='tag_blogpost_list'),
    path('user/<slug:slug>', views.AuthorBlogPostList.as_view(), name='author_blogpost_list'),
    path('saved/', views.SavedBlogPostList.as_view(), name='saved_blogpost_list'),

    path('create/', views.BlogPostCreate.as_view(), name='blogpost_create'),
    path('<slug:slug>/', views.BlogPostDetail.as_view(), name='blogpost_detail'),
    path('update/<slug:slug>/', views.BlogPostUpdate.as_view(), name='blogpost_update'),
    path('delete/<slug:slug>/', views.BlogPostDelete.as_view(), name='blogpost_delete'),

    path('create-comment/<slug:slug>/<str:content>/', views.create_comment, name='create_comment'),
    path('delete-comment/<int:commentId>/', views.delete_comment, name='delete_comment'),

    path('save-blogpost/<slug:slug>/', views.save_blogpost, name='save_blogpost'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.loginView, name='login'),
    path('register/', views.registerView, name='register'),
    path('logout/', views.logoutView, name='logout'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>{% block title %}Title{% endblock title %}</title>
</head>
<body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'blogs:blogpost_list' %}">BLOG APP</a>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">

                      <li class="nav-item active">
                        <a class="nav-link" href="{% url 'blogs:tag_list' %}">Tags</a>
                      </li>
                      <li class="nav-item active">
                        <a class="nav-link" href="{% url 'blogs:blogpost_create' %}">Create BP</a>
                      </li>

                    
                    </ul>

                    <ul class="navbar-nav ml-auto">
                        {% if request.user.is_authenticated %}
                        <li class="nav-item active">
                          <a class="nav-link" href="{% url 'blogs:saved_blogpost_list' %}">Saved Posts</a>
                        </li>
                        <li class="nav-item active">
                          <a class="nav-link" href="{% url 'blogs:author_blogpost_list' request.user %}">My Posts</a>
                        </li>
                        <li class="nav-item active">
                          <span class="nav-link">Hello {{request.user}}</span>
                        </li>
                        <li class="nav-item active">
                          <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                        </li>
                        {% else %}
              
                        <li class="nav-item active">
                          <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                        </li>

                        <li class="nav-item active">
                          <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                        </li>
                        {% endif %}                        
                        </ul>
                </div>
            </div>
        </nav>

        <div class="container mt-5">

            {% if messages %}
                {% for message in messages %}
                  {% if message.tags == 'error' %}
                    <div class="alert alert-danger">{{ message }}</div>
                  {% else %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                  {% endif %}
                {% endfor %}
            {% endif %}

            {% block body %}{% endblock body %}
        </div>


    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    

    <script src="{% static 'js/save_bp.js' %}"></script>
    <script src="{% static 'js/comments.js' %}"></script>
</body>
</html>

templates/basic.html
{% extends 'base.html' %}
{% load static %}


{% block title %}{% endblock title %}




{% block body %}
    <h1>Hello World</h1>
{% endblock body %}